#===============================================================
# DMXIS Startup Macro (c) 2010 db audioware limited
#
# This is called on DMXIS startup, and initialises any global
# Python requirements across all macros 
#
# DO NOT EDIT THIS FILE!!!
#===============================================================

#---------------------------------------------------
# Import DMXIS C extension module
#---------------------------------------------------

import _DmxApi
from _DmxApi import *

#---------------------------------------------------
# Redirect stdout/stderr to DMXIS extension module 
#    def write(self, s): dmxis.write(s) 
#---------------------------------------------------
import sys
class Redirect:
    def write(self, s): _DmxApi.DmxisWrite(s) 
sys.stdout = Redirect()
sys.stderr = Redirect()

print "Initialising DMXIS Python engine..."

#---------------------------------------------------
# Import DMXIS RGB utility methods
#---------------------------------------------------
import System.RGB
from System.RGB import *

#---------------------------------------------------
# Import general helper methods
#---------------------------------------------------
import System.Helpers
from System.Helpers import *

print "Ready!"
print ""
